version: '3'
services:
  airflow-init:
    image: dithub-airflow
    command: db migrate
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags:Z
      - ./dlt_pipeline.py:/opt/airflow/dlt_pipeline.py:Z
      - ./.dlt:/opt/airflow/.dlt:Z
      - ./.env:/opt/airflow/.env:Z
      - ./github:/opt/airflow/github:Z
      - ./github_pipeline.duckdb:/opt/airflow/github_pipeline.duckdb:Z

  airflow-webserver:
    image: dithub-airflow
    command: standalone
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_ADMIN_USER=admin
      - AIRFLOW_ADMIN_PASSWORD=admin
    volumes:
      - ./dags:/opt/airflow/dags:Z
      - ./dlt_pipeline.py:/opt/airflow/dlt_pipeline.py:Z
      - ./.dlt:/opt/airflow/.dlt:Z
      - ./.env:/opt/airflow/.env:Z
      - ./github:/opt/airflow/github:Z
      - ./github_pipeline.duckdb:/opt/airflow/github_pipeline.duckdb:Z
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    depends_on:
      - airflow-init
